<?php

namespace AppBundle\Repository;

/**
 * TaskmanagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskmanagementRepository extends \Doctrine\ORM\EntityRepository
{
}
